image: gsiupm/dockermake:latest


# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay
  DOCKERFILE: Dockerfile
  VERSION: $CI_BUILD_REF

stages:
  - test
  - push
  - clean

.test: &test_definition
  stage: test
  script:
    - make -e test-$PYTHON_VERSION
    
test-3.5:
  <<: *test_definition
  variables:
    PYTHON_VERSION: "3.5"

test-2.7:
  <<: *test_definition
  variables:
    PYTHON_VERSION: "2.7"


.image: &image_definition
  stage: push
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - make -e push-$PYTHON_VERSION
  only:
    - tags
    - triggers

push-3.5:
  <<: *image_definition
  variables:
    PYTHON_VERSION: "3.5"
    VERSION: $CI_BUILD_TAG

push-2.7:
  <<: *image_definition
  variables:
    PYTHON_VERSION: "2.7"
    VERSION: $CI_BUILD_TAG

push-main:
  <<: *image_definition
  variables:
    PYTHON_VERSION: main
    VERSION: $CI_BUILD_TAG

push-latest:
  <<: *image_definition
  variables:
    PYTHON_VERSION: latest
    VERSION: $CI_BUILD_TAG
  only:
    - master
    - tags
    - triggers

clean :
  stage: clean
  script:
    - make -e clean
  only:
    - master